### ISSUE TITLE
Make it with language selection and logging

### ISSUE THREAD

**Issue by clubdesarrolladores** [certificationy/certificationy#32]
Hi,
This tool is very usefull for me.
Can be used to take tests.
But i need it in spanish with logs or output by session (eg: user name at least) to take test.

There is some advance in this topics already?

Thanks.

**Comment by mickaelandrieu** [comment]
Hi @clubdesarrolladores, 
language selection won't be part of certificationy project but you can make a PR to add a Psr\Log logguer if you need it.

Regards,
