### ISSUE TITLE
Doctrine questions are included but it is not covered in the Symfony2 certification exam

### ISSUE THREAD

**Issue by eriwin** [certificationy/certificationy#43]
See: http://sensiolabs.com/en/symfony/certification/faq.html

The exam does not support any persistence frameworks like Doctrine or Propel. The exam only focuses on the Symfony core concepts (including Twig).

Although asking questions about Doctrine is a good thing. When working with Symfony you will probably need this knowledge but because it is not covered in the exam it could confuse people when using this tool to study for the exam.

**Comment by mickaelandrieu** [comment]
@eriwin I'm now the official maintainer.

In my opinion, this software should be totaly decoupled from Symfony2 certification to become a tool to prepare certifications.

Like in tools like Anki.

In fact, we should remove ``data`` folder from certificationy and allow the app to choose the correct folder.

For example, we can think about a package of type "certificationy" and everyone can make his own tests and this way everyone can build web service on top of certificationy model.

**Comment by mickaelandrieu** [comment]
See ``uncoupled-data`` branch, so we should separate doctrine-php questions in their own "deck".
