### ISSUE TITLE
Wrong answer in validation.yml

### ISSUE THREAD

**Issue by ghostika** [certificationy/certificationy#45]
The first question:

In order to use validation group, which interface will you implement on your object?

Is wrong, cause you don't need any interface, but what all the 4 answer, and the marked TRUE answer suggest, the right question wanted to be:
In order to use Group Sequence in validation, which interface will you implement on your object?
And then the right answer is GroupSequenceProviderInterface

**Comment by mickaelandrieu** [comment]
ping ?
