### ISSUE TITLE
Website fails with slashes

### ISSUE THREAD

**Issue by garak** [certificationy/certificationy#53]
There are some weird strings in http://www.certificationy.com/, likely due to incorrect slash escaping.
Examples:

use myapp\utilsaroo

Symfony\Bridge\Monolog og oggerInterface

**Comment by mickaelandrieu** [comment]
Hi @garak ,

certificationy.com is not part of this organisation, you should take a look to @ProPheT777 certificationy-webplatform project.

Regards
