### ISSUE TITLE
proposal to support MongoDB certification

### ISSUE THREAD

**Issue by ProPheT777** [certificationy/certificationy#58]
https://university.mongodb.com/exams

**Comment by mickaelandrieu** [comment]
I'm totaly :+1:

**Comment by mickaelandrieu** [comment]
@ProPheT777 what is the status of this proposal ? Do you need I create a new repository ?

**Comment by ProPheT777** [comment]
I have no time to create a set of questions and i'm not expert in mongodb world that was just a proposal.

But I think you can create repository to encourage people to contribute or start the support of this certification :)

**Comment by mickaelandrieu** [comment]
agree :) done!

**Comment by mickaelandrieu** [comment]
@ProPheT777 no one sounds really interested to contribute to MongoDB pack, at least in an official and open source way.

Closed :)
