### ISSUE TITLE
proposal to support Magento certification

### ISSUE THREAD

**Issue by xiris** [certificationy/certificationy#61]
Hallo, I would like to propose create a repository for Magento certification.

http://magento.com/training/catalog/certified-developer-and-developer-plus#.VdbduXW1FBc

**Comment by mickaelandrieu** [comment]
Hi,

you need to create a repository that follow the same architecture than symfony|mongodb|php-pack.

Then add your composer package as a dependency of Certificationy CLI and update the config.yaml file to activate your new Set of questions.

If the content is accurate, we can then make this repository "official" and you may give the ownership to the organisation (and then have access to continue to manage it).

I realy need to document it, indeed :)

**Comment by xiris** [comment]
Will set up and I let you know.
Thank you :)

**Comment by mickaelandrieu** [comment]
You're welcome :)

Don't forget to declare set up your package type as "certificationy-pack", because we will (probably) use it to list all available sets of questions :)

**Comment by mickaelandrieu** [comment]
@xiris if you have started you deck, tell me :)

**Comment by mickaelandrieu** [comment]
time to close this issue :)
