### ISSUE TITLE
[Improvement] Implements EventDispatcher optional dependency

### ISSUE THREAD

**Issue by vincentchalamon** [certificationy/certificationy#67]
- [ ] Add `symfony/event-dispatcher` optional dependency
- [ ] Add a sample controller to fill in a `Set`: `startAction`, `questionAction`, `endAction`
- [ ] Dispatch events: `certificationy.set_start`, `certificationy.set_end`, `certificationy.question_start`, `certificationy.question_end`

**Comment by mickaelandrieu** [comment]
@vincentchalamon I'm totaly open to this kind of improvement: if you have time, make a PR.

First step could be to add duration without any chance to stop the Set workflow.
Second step could be to add Conditions (and probably add Events ? ^^).

Good luck for certification :p

**Comment by vincentchalamon** [comment]
I'll definitively open some PRs for the improvement issues I've just created 😉

> First step could be to add duration without any chance to stop the Set workflow.
> Second step could be to add Conditions (and probably add Events ? ^^).

Can you explain me more about your steps?

I was thinking about an option on `Set` object to define a maximum duration to answer all questions. For example, if limit is set to 30, test will finish after 30 minutes whatever student has answered all questions or not ^^ It's related to [this issue](https://github.com/certificationy/certificationy/issues/65)

For current issue, I was just thinking about a free text on `Set` object to add a description, like:
```
This test is about PHP skills since PHP 5.5. You have 30mn to complete it.
You are able to use any resource you want: Internet, online documentations…
```

**Comment by vincentchalamon** [comment]
BTW, don't hesitate to comment my other improvement issues if you estimate they don't need to be in this project

**Comment by mickaelandrieu** [comment]
@vincentchalamon for me all your improvements are good ideas :+1: 

First step could be implement `getDuration` to both `Question` and `Set` objects: obviously the duration of the Set is incremented by the duration of each Question.

I'm not sure about how to implement a very simple way to make the Set stops, this is why I suggest some events (if Event Dispatcher is available), to let everyone decide if a `Set` have to be stopped or continued.

Regarding the free text, do we need it in this library or in the implementation ? (the cli app)

**Comment by vincentchalamon** [comment]
Following your idea, I should only need to integrate an EventDispatcher & dispatch some events to manage everything: save question duration, increment set duration, & let user do whatever he wants at any event (for example send an email to admin when set is finished).

I imagine following events:
- set start
- question start
- question end
- set end

This improvement should manage both issues #65 #66

**Comment by mickaelandrieu** [comment]
:+1: go for it, I wont refuse.

Still, I'd like to see the event dispatcher *to be an optional dependency*: I'm totaly boring on this point, as you may know xD

**Comment by vincentchalamon** [comment]
I'm afraid that before implementing EventDispatcher, I may need some features, like a controller to answer a `Set` (required to send events): startAction, questionAction, endAction…

This controller can be a simple class (so without any dependency) that can be manually loaded by user in its final project.

**Comment by mickaelandrieu** [comment]
Ok, this should be probably done outside of this library at some point.

Thank for your feedback!
