### ISSUE TITLE
[Improvement] Add Doctrine support

### ISSUE THREAD

**Issue by vincentchalamon** [certificationy/certificationy#69]

**Comment by mickaelandrieu** [comment]
@vincentchalamon arf I'm not against a bundle, and I'm aware there is already a Symfony application https://github.com/ProPheT777/certificationy-web-platform

The main issue is mainly my lack of need and of time ^^

If you have to priorize, I'd like to say that the doctrine support could be a great improvement (but need to stay an optional dependency, so I'm *against* annotations in this case.

**Comment by vincentchalamon** [comment]
I totally agree with you about Doctrine as optional dependency & not using annotations in a generic library!

I'll first work on Doctrine bridge, and see later (in another issue) if there is a need to bridge Symfony
